[workspace]
members = [
  "parser",
  "repl",
]

[package]
name = "rusty-monkey"
version = "0.1.0"
authors = ["Gerard Abelló Serras <gerardabello@gmail.com>"]
edition = "2018"

[dependencies]
parser = { version = "0.1", path = "parser" }
repl = { version = "0.1", path = "repl" }
