[workspace]
members = [
  "lexer",
  "repl",
]

[package]
name = "rusty-monkey"
version = "0.1.0"
authors = ["Gerard Abelló Serras <gerardabello@gmail.com>"]
edition = "2018"

[dependencies]
lexer = { version = "0.1", path = "lexer" }
repl = { version = "0.1", path = "repl" }
